on:
  pull_request:
  push:
    branches:
      - main

name: Go
jobs:
  golangci:
    name: golang-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          # cache-dependency-path: go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=10m

  vet:
    name: vet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          # cache-dependency-path: go.sum

      - name: Vet
        run: go vet ./...

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          # cache-dependency-path: go.sum

      - name: Test
        run: |
          go test -race -coverprofile=unit-coverage.out -covermode=atomic ./...

      - uses: actions/upload-artifact@v4
        with:
          name: unit-test-coverage
          path: unit-coverage.out
